---
- name: Build tagged VMs
  hosts: vps_runner
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Install dependencies
      block:
        - name: Install dependencies
          include_tasks: install_dependencies.yml
      become: true

    - name: Install source and submodules
      block:
        - name: Install source
          include_tasks: install_source.yml

    - name: Clean existing VirtualBox VMs
      block:
        - name: Clean existing vbox VMs
          include_tasks: clean_existing_vbox_vms.yml

    - name: Create VM from tag
      block:
        - name: Create VM
          include_tasks: create_vm.yml

    - name: Start new VirtualBox VMs
      block:
        - name: Start new vbox VMs
          include_tasks: start_new_vbox_vms.yml
