---
- name: Get graphical target default
  shell:  "systemctl get-default"
  register: systemdefault

- name: Install GUI
  block:
    - name: Install apt packages
      apt:
        pkg:
          - task-xfce-desktop
        update_cache: true
    
    - name: Upgrade apt packages
      apt:
        upgrade: full
    
    - name: "Set default to graphical target"
      command: "systemctl set-default graphical.target"
    
    - name: Reboot VPS for stray loop devices
      reboot:
        reboot_timeout: 60
  when: "'graphical' not in systemdefault.stdout"
