---
- name: Create install_source script
  template:
    src: ./roles/common/templates/install_source.sh
    dest: /home/ansible/install_source.sh
    mode: 0744

- name: Run install_source script for commit
  shell: "/home/ansible/install_source.sh {{ GIT_REPO }} {{ REF_NAME }} >> /home/ansible/log.txt 2>&1"
