dist: bionic

sudo: required
language: generic

before_install:
  - sudo apt-get -q update
  - sudo apt-get -y install apt-cacher-ng net-tools

services:
  - docker

jobs:
  include:
    - stage: git clone test
      script: ./help-steps/ci_git_clone_test
    - stage: Debian docker based package building test
      env: TRAVIS_DEBIAN_GIT_BUILDPACKAGE=./help-steps/ci_package_build_test
      script: wget -O- https://raw.githubusercontent.com/adrelanos/travis.debian.net/gh-pages/script.sh | sh -
    - stage: Debian docker based package installation test
      env: TRAVIS_DEBIAN_GIT_BUILDPACKAGE=./help-steps/ci_test
      script: wget -O- https://raw.githubusercontent.com/adrelanos/travis.debian.net/gh-pages/script.sh | sh -
    - stage: mmdebstrap based test without apt-cacher-ng
      script: ./help-steps/ci_test2
    - stage: mmdebstrap based test with apt-cacher-ng
      script: ./help-steps/ci_test3
    - stage: stages test
      script:
        - /bin/true

if:
  tag IS blank

env:
  global:
  - TRAVIS_DEBIAN_NO_BUILD=true
  - TRAVIS_DEBIAN_DISTRIBUTION=buster
  ## required for firmware-nonfreedom
  - TRAVIS_DEBIAN_COMPONENTS="main contrib non-free"
  - TRAVIS_DEBIAN_SECURITY_UPDATES=true
  ## no longer global
  #- TRAVIS_DEBIAN_GIT_BUILDPACKAGE=./help-steps/ci_test
  - TRAVIS_DEBIAN_GIT_BUILDPACKAGE_OPTIONS=" "
  #- TRAVIS_DEBIAN_AUTOPKGTEST=true
  - TRAVIS_DEBIAN_NETWORK_ENABLED=true
  - TRAVIS_DEBIAN_EXTRA_PACKAGES="lintian sudo"
  - TRAVIS_DEBIAN_BUILD_DIR=/home/travis/build-dir
  - TRAVIS_DEBIAN_TARGET_DIR=/home/travis/build-result
