---
- name: Install xfce
  apt:
    pkg:
      - xfce4
      - xfce4=goodies
      - tightvncserver
      - dbus-x11
    update_cache: true
  become: true

# TODO: Configure TightVNC password
# - name: Install tightvnc
#   expect:
#     command: vncserver
#     responses:
#       Question:
#         - response1
#         - response2
#         - response3

# https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-debian-11
