---
- name: Install source code for commit
  include_tasks: install_source.yml

# - name: Build VMs from tag
#   include_tasks: build_vms_from_tag.yml

- name: Install GUI
  include_tasks: install_gui.yml
