---
- name: Start new VirtualBox VMs
  environment:
    DISPLAY: "localhost:1"
  block:
    - name: Start VNC display
      shell: "vncserver"

    - name: Add xhost
      shell: "xhost +"

    - name: Start gateway VM
      shell: "VBoxManage startvm Whonix-Gateway-LXQt"

    - name: Start workstation VM
      shell: "VBoxManage startvm Whonix-Workstation-LXQt"
