---
- name: Start new VirtualBox VMs
  environment:
    DISPLAY: "localhost:1"
  block:
    - name: Add xhost
      shell: "xhost +"

    - name: Add VRAM and RAM on Workstation
      shell: 'VBoxManage modifyvm Whonix-Workstation-XFCE --vram 128 --ram 8192'

    - name: Add RAM on Gateway
      shell: 'VBoxManage modifyvm Whonix-Workstation-Gateway --ram 2096'

    - name: Start gateway VM
      shell: "VBoxManage startvm Whonix-Gateway-XFCE"

    - name: Start workstation VM
      shell: "VBoxManage startvm Whonix-Workstation-XFCE"

    - name: Wait for VMs to boot and connect to TOR
      pause:
        minutes: 3
