---
- name: Run automated_builder
  hosts: vps_runner
  gather_facts: false
  vars_files:
    - ./roles/common/vars/main.yml
    - ./roles/common/vars/secrets.yml

  tasks:
    - name: Include common role
      include_role:
        name: common

    - name: Include small-resource role
      include_role:
        name: small-resource
      when: REF_TYPE != 'tag'

    - name: Include large-resource role
      include_role:
        name: small-resource
      when: REF_TYPE == 'tag'
# - name: Create VMs from tag
#   include_tasks: create_vms_from_tag.yml
#   when: REF_TYPE == 'tag'

# - name: Create VMs from commit
#   include_tasks: create_vms_from_commit.yml
#   when: REF_TYPE != 'tag'

# - name: Start new VirtualBox VMs
#   include_tasks: start_new_vbox_vms.yml
