---
- name: Run automated_builder
  hosts: vps_runner
  gather_facts: false
  vars_files:
    - ./roles/common/vars/main.yml
    - ./roles/common/vars/secrets.yml

  tasks:
    - name: Include common role
      include_role:
        name: common

    - name: Include small-resource role
      include_role:
        name: small-resource
      when: REF_TYPE != 'tag'

    - name: Include large-resource role
      include_role:
        name: small-resource
      when: REF_TYPE == 'tag'
