---
- name: Gather build logs
  hosts: vps_runner
  gather_facts: false
  vars:
    VPS_IP: "{{ lookup('env', 'VPS_IP' )}}"
  vars_files:
    - ../vars/main.yml
    - ../vars/secrets.yml

  tasks:
    - name: Get droplet IP
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ DO_API_TOKEN }}"
        name: "automated-builder-vps"
      delegate_to: localhost
      register: automated_builder_vps

    - name: Debug VPS_IP setting
      debug:
        var: automated_builder_vps

    - name: Set VPS_IP
      set_fact:
        VPS_IP: "{{ automated_builder_vps.data[0].networks.v4 | selectattr('type', 'equalto', 'public') | map(attribute='ip_address') | first }}"

    - name: Gather facts
      setup:

    - name: Copy logs
      fetch:
        src: "/home/ansible/{{ item }}"
        dest: "../logs/{{ item }}"
      with_items:
        - 'install_verified_source.log'
        - 'build.log'
