---
- name: Install dependencies
  become: true
  block:
    - name: Install apt packages
      apt:
        pkg:
          - git
          - time
          - curl
          - lsof
          - apt-cacher-ng
          - lsb-release
          - fakeroot
          - dpkg-dev
          - fasttrack-archive-keyring
          - dnsutils
          - software-properties-common
          - python3-pip
        update_cache: true

    - name: Install pexpect
      pip:
        name: pexpect

    - name: Upgrade to latest kernel
      apt:
        upgrade: dist

    - name: Reboot VPS
      reboot:

    - name: Register uname
      shell: "uname -r"
      register: uname

    - name: Install new kernel headers
      apt:
        name: "linux-headers-{{ uname.stdout }}"

    - name: Install VirtualBox
      include_tasks: install_virtualbox.yml
