---
- name: Install dependencies
  become: true
  block:
    - name: Check droplet status
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ DO_API_TOKEN }}"
        name: automated-builder-vps
      register: droplet_facts

    - name: Debug droplet_facts
      debug:
        var: droplet_facts

    - name: Install apt packages
      apt:
        pkg:
          - git
          - time
          - curl
          - lsof
          - apt-cacher-ng
          - lsb-release
          - fakeroot
          - dpkg-dev
          - fasttrack-archive-keyring
          - dnsutils
          - software-properties-common
        update_cache: true
