---
- name: Install dependencies
  become: true
  block:
    - name: Update and upgrade
      apt:
        update_cache: true
        upgrade: true
        allow_change_held_packages: true

    - name: Install apt packages
      apt:
        pkg:
          - git
          - time
          - curl
          - lsof
          - apt-cacher-ng
          - lsb-release
          - fakeroot
          - dpkg-dev
          - fasttrack-archive-keyring
          - dnsutils
          - software-properties-common
        update_cache: true

    - name: Run maintained VirtualBox installation script
      become: false
      shell: "/home/ansible/derivative-maker/packages/kicksecure/usability-misc/usr/bin/installer-dist --non-interactive --virtualbox-only --log-level=info > /home/ansible/virtualbox_install.log"
