---
- name: Install VirtualBox
  become: true

  block:
    - name: Import VirtualBox GPG key
      get_url:
        dest: "/root/{{ VBOX_ASC_KEY.name }}.asc"
        url: "{{ VBOX_ASC_KEY.url }}"

    - name: Create gpg file
      shell: "gpg --dearmor /root/{{ VBOX_ASC_KEY.name }}.asc > {{ VBOX_ASC_KEY.name }}.gpg"

    - name: Move gpg key to shared keyrings
      copy:
        src: "/root/{{ VBOX_ASC_KEY.name }}.asc.gpg"
        dest: "/usr/share/keyrings/{{ VBOX_ASC_KEY.name }}.asc.gpg"
        remote_src: true

    - name: Register LSB release
      shell: "lsb_release -cs"
      register: lsb_release

    - name: Add VirtualBox apt repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/{{ VBOX_ASC_KEY.name }}.asc.gpg] http://download.virtualbox.org/virtualbox/debian {{ lsb_release.stdout }} contrib"
        state: present

    - name: Install VirtualBox apt repository
      apt:
        name: "virtualbox-7.0"
        update_cache: true
