---
- name: Install dependencies
  become: true
  block:
    - name: Wait for cloud-init / user-data to finish
      command: cloud-init status --wait
      changed_when: false

    - name: Install apt packages
      apt:
        pkg:
          - git
          - time
          - curl
          - lsof
          - apt-cacher-ng
          - lsb-release
          - fakeroot
          - dpkg-dev
          - fasttrack-archive-keyring
          - dnsutils
          - software-properties-common
        update_cache: true
