---
- name: Configure local environment
  include_tasks: configure_local_environment.yml

- name: Generate inventory
  include_tasks: generate_inventory.yml

- name: Bootstrap VPS
  include_tasks: bootstrap_vps.yml

- name: Gather facts
  setup:

- name: Install dependencies
  include_tasks: install_dependencies.yml
