---
- name: Generate inventory
  include_tasks: generate_inventory.yml

- name: Configure local environment
  include_tasks: configure_local_environment.yml

- name: Bootstrap VPS
  include_tasks: bootstrap_vps.yml

- name: Gather facts
  setup:

- name: Install dependencies
  include_tasks: install_dependencies.yml

# TODO: break in to small resource and large resource roles
- name: Install source and submodules
  include_tasks: install_source.yml

- name: Clean existing VirtualBox VMs
  include_tasks: clean_existing_vbox_vms.yml
