REF_TYPE: "{{ lookup('env', 'github.ref_type') }}"
GIT_REPO: "{{ lookup('env', 'github.repositoryUrl') }}"
REF_NAME: "{{ lookup('env', 'github.base_ref') }}"
VBOX_ASC_KEY:
  name: 'oracle_vbox_2016'
  url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
